import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.scss";
import { logout } from "../redux/actions/Authentication";
import { useDispatch, useSelector } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const authState = useSelector((state) => state.authentication);

  useEffect(() => {
    console.log(authState);
  }, [authState]);

  const [showMenu, setShowMenu] = useState(false);

  const handleMobileMenu = () => {
    setShowMenu(!showMenu);
    if (showMenu) {
      document.body.style.overflow = "auto";
    } else {
      document.body.style.overflow = "hidden";
    }
  };

  const handleLogout = () => {
    dispatch(logout());
  };

  return (
    <div className={styles.container} style={{ overflowY: "hidden" }}>
      <Head>
        <title>Brainup.in - For students. By students</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, user-scalable=no"
        ></meta>
      </Head>

      <div className={styles.header}>
        <span className={styles.logo}>
          <Image
            src="/logo/main.png"
            width={100}
            height={50}
            objectFit="contain"
          />
        </span>
        <div className={styles.mobileLogo} style={{ width: 30, height: 30 }}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 406.022 406.022"
            width={30}
            height={30}
          >
            <title>brainly logo</title>
            <path
              d="M-.035 405.581l406.08-69.668V.661L-.035 70.908v334.673z"
              fill="#00a451"
            />
            <path
              fill="#fff"
              d="M253.902 184.351c11.514-6.618 24.802-23.077 24.802-43.644 0-20.585-13.288-31.104-26.078-34.017-12.773-2.915-29.39-1.292-44.732 1.344l-89.549 15.481v41.905l16.688-2.794v93.558l-16.688 2.79v41.91l103.613-17.935c16.62-2.869 34.506-9.823 45.992-19.56 11.513-9.682 19.727-22.687 19.727-43.246 0-20.572-13.323-33.694-33.775-35.792zm-61.35-31.734l11.507-2.008c6.404-1.106 8.953-1.555 12.78.363 3.836 1.899 5.119 4.772 5.119 9.396a13.065 13.065 0 0 1-5.118 10.929c-3.828 3.217-6.377 3.92-12.78 5.034l-11.508 1.985zm31.964 83.64c-3.841 3.24-6.393 4.466-12.781 5.572l-19.183 3.323v-28.266l19.183-3.313c6.388-1.132 8.94-1.064 12.78.834 3.82 1.888 5.111 5.55 5.111 10.163a14.51 14.51 0 0 1-5.11 11.688z"
            />
          </svg>
        </div>

        <div className={styles.options}>
          <span onClick={() => router.push("/auth/login")}>LOGIN</span>
          <span onClick={() => router.push("/auth/signup")}>JOIN FOR FREE</span>
        </div>
        <div className={styles.mobileOptions}>
          <span style={{ width: 24, height: 24 }} onClick={handleMobileMenu}>
            {showMenu ? (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="black"
                width="24"
                height="24"
              >
                <path d="M13.41,12l6.3-6.29a1,1,0,1,0-1.42-1.42L12,10.59,5.71,4.29A1,1,0,0,0,4.29,5.71L10.59,12l-6.3,6.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0L12,13.41l6.29,6.3a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42Z" />
              </svg>
            ) : (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <g data-name="Layer 2">
                  <g data-name="menu">
                    <rect
                      width="24"
                      height="24"
                      opacity="0"
                      transform="rotate(180 12 12)"
                    />
                    <rect
                      width="18"
                      height="2"
                      x="3"
                      y="11"
                      rx=".95"
                      ry=".95"
                    />
                    <rect
                      width="18"
                      height="2"
                      x="3"
                      y="16"
                      rx=".95"
                      ry=".95"
                    />
                    <rect width="18" height="2" x="3" y="6" rx=".95" ry=".95" />
                  </g>
                </g>
              </svg>
            )}
          </span>
        </div>
      </div>

      <div className={styles.bannerContainer}>
        <div className={styles.banner}>
          <div className={styles.bannerText}>
            <h1>Go from questioning to understanding.</h1>
            <p>
              Brainup is the knowledge-sharing community where students and
              experts put their heads together to crack their toughest homework
              questions.
            </p>
            <div className={styles.auth}>
              <span onClick={() => router.push("/auth/login")}>LOGIN</span>
              <span onClick={() => router.push("/auth/signup")}>JOIN NOW</span>
            </div>
          </div>

          <div className={styles.bannerImage}>
            <Image
              src="/images/home.png"
              width={500}
              height={500}
              alt="banner"
            />
          </div>
        </div>
      </div>

      <main className={styles.main}>
        <span className={styles.icon}>
          <svg
            id="SvgjsSvg1001"
            width="56"
            height="56"
            xmlns="http://www.w3.org/2000/svg"
            version="1.1"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            xmlnsSvgjs="http://svgjs.com/svgjs"
          >
            <defs id="SvgjsDefs1002"></defs>
            <g id="SvgjsG1008" transform="matrix(1,0,0,1,0,0)">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="56"
                height="56"
                viewBox="0 0 16 16"
              >
                <path
                  fill="#24a865"
                  fill-rule="evenodd"
                  d="M15.67 7.06l-1.08-1.34c-.17-.22-.28-.48-.31-.77l-.19-1.7a1.51 1.51 0 0 0-1.33-1.33l-1.7-.19c-.3-.03-.56-.16-.78-.33L8.94.32c-.55-.44-1.33-.44-1.88 0L5.72 1.4c-.22.17-.48.28-.77.31l-1.7.19c-.7.08-1.25.63-1.33 1.33l-.19 1.7c-.03.3-.16.56-.33.78L.32 7.05c-.44.55-.44 1.33 0 1.88l1.08 1.34c.17.22.28.48.31.77l.19 1.7c.08.7.63 1.25 1.33 1.33l1.7.19c.3.03.56.16.78.33l1.34 1.08c.55.44 1.33.44 1.88 0l1.34-1.08c.22-.17.48-.28.77-.31l1.7-.19c.7-.08 1.25-.63 1.33-1.33l.19-1.7c.03-.3.16-.56.33-.78l1.08-1.34c.44-.55.44-1.33 0-1.88zM6.5 12L3 8.5 4.5 7l2 2 5-5L13 5.55 6.5 12z"
                  class="color000 svgShape"
                ></path>
              </svg>
            </g>
          </svg>
        </span>
        <h1 className={styles.title}>
          Tap into the brainpower of thousands of experts worldwide
        </h1>
      </main>

      <div
        className={styles.mobileMenu}
        style={{
          opacity: showMenu ? 1 : 0,
          zIndex: showMenu ? 999 : -99,
          visibility: showMenu ? "visible" : "hidden",
        }}
      >
        <div className={styles.mobileMenuItem}>
          <h1 className={styles.title}>Let's start sharing knowledge</h1>
          <div className={styles.auth}>
            <span onClick={() => router.push("/auth/login")}>LOGIN</span>
            <span onClick={() => router.push("/auth/signup")}>JOIN NOW</span>
          </div>
        </div>
      </div>
    </div>
  );
}
