export const UPDATE_USER_DESCRIPTION_REQUEST =
  "UPDATE_USER_DESCRIPTION_REQUEST";
export const UPDATE_USER_DESCRIPTION_SUCCESS =
  "UPDATE_USER_DESCRIPTION_SUCCESS";
export const UPDATE_USER_DESCRIPTION_FAIL = "UPDATE_USER_DESCRIPTION_FAIL";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAIL = "UPDATE_AVATAR_FAIL";

export const GET_CONVERSATIONS_REQUEST = "GET_CONVERSATIONS_REQUEST";
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";

export const GET_QUESTION_BY_ID_REQUEST = "GET_QUESTION_BY_ID_REQUEST";
export const GET_QUESTION_BY_ID_SUCCESS = "GET_QUESTION_BY_ID_SUCCESS";
export const GET_QUESTION_BY_ID_FAIL = "GET_QUESTION_BY_ID_FAIL";

export const GET_ANSWER_BY_ID_REQUEST = "GET_ANSWER_BY_ID_REQUEST";
export const GET_ANSWER_BY_ID_SUCCESS = "GET_ANSWER_BY_ID_SUCCESS";
export const GET_ANSWER_BY_ID_FAIL = "GET_ANSWER_BY_ID_FAIL";
